=== heurtematte/hornetmobility/WEB-INF/classes/menu.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="menu-item" type="menuItemType"></xs:element>
    
	<xs:complexType name="menuItemType">
	    <xs:sequence minOccurs="0" maxOccurs="unbounded">
          <xs:element name="menu-item" type="menuItemType"></xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="id" use="required" />
		<xs:attribute type="xs:string" name="href" use="optional" />
		<xs:attribute type="xs:string" name="visibleDansMenu" use="optional" />
		<xs:attribute type="xs:string" name="visibleDansPlan" use="optional" />
		<xs:attribute type="xs:string" name="visibleDansFilAriane" use="optional" />
		<xs:attribute type="xs:string" name="rolesAutorises" use="optional" />
	</xs:complexType>

	<xs:element name="pagelet">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="root">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute type="xs:string" name="id" />
								<xs:attribute type="xs:string" name="href" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="menu">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="menu-item" maxOccurs="unbounded" minOccurs="0" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== heurtematte/hornetmobility/WEB-INF/classes/menu.xml
<?xml version="1.0" encoding="utf-8" ?>
<pagelet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="menu.xsd">
    <root 
        id="root"
        href="/dyn/protected/accueil.html">
    </root>
    <menu>
        <menu-item
            id="menu.accessibilite"
            href="/dyn/protected/accessibilite.html" 
            visibleDansMenu="false">
        </menu-item>
        <menu-item
            id="menu.aide"
            href="/dyn/protected/aide.html" 
            visibleDansMenu="false">
        </menu-item>
        <menu-item
            id="menu.planSite"
            href="/dyn/protected/planSite.html" 
            visibleDansMenu="false" visibleDansPlan="false">
        </menu-item>
        <menu-item
            id="menu.contact"
            href="/dyn/protected/contact/formContact.html" 
            visibleDansMenu="false" visibleDansPlan="false">
        </menu-item>
        <menu-item
            id="menu.accueil"
            href="/dyn/protected/accueil.html"
            visibleDansFilAriane="false"
            rolesAutorises="ROLE_AppliTuto_USER">
        </menu-item>
        <menu-item
            id="menu.partenaires"
            rolesAutorises="ROLE_AppliTuto_USER,ROLE_AppliTuto_ADMIN">
            <menu-item
                id="menu.partenaires.liste"
                href="/dyn/protected/partenaire/formRecherche.html"
                rolesAutorises="ROLE_AppliTuto_USER,ROLE_AppliTuto_ADMIN">
                <menu-item 
                    id="menu.partenaires.fichePartenaire" 
                    visibleDansMenu="false" visibleDansPlan="false"
                    rolesAutorises="ROLE_AppliTuto_USER">
                </menu-item>
                <menu-item 
                    id="menu.partenaires.ajoutPartenaire" 
                    visibleDansMenu="false" visibleDansPlan="false"
                    rolesAutorises="ROLE_AppliTuto_USER">
                </menu-item>
                <menu-item 
                    id="menu.partenaires.editionPartenaire" 
                    visibleDansMenu="false" visibleDansPlan="false"
                    rolesAutorises="ROLE_AppliTuto_USER">
                </menu-item>
            </menu-item>
            <menu-item 
                id="menu.partenaires.arborescence"
                href="/dyn/protected/partenaire/arborescence.html"
                rolesAutorises="ROLE_AppliTuto_USER">
            </menu-item>
        </menu-item>
        <menu-item
            id="menu.administration"
            rolesAutorises="ROLE_AppliTuto_ADMIN">
	        <menu-item
	           id="menu.administration.secteurs"
	           rolesAutorises="ROLE_AppliTuto_ADMIN">
	           <menu-item
	               id="menu.administration.secteurs.liste"
	               href="/dyn/protected/administration/secteur/liste.html"
	               rolesAutorises="ROLE_AppliTuto_ADMIN">
	               <menu-item
	                   id="menu.administration.secteurs.ajoutSecteur" 
                       visibleDansMenu="false" visibleDansPlan="true"
                       rolesAutorises="ROLE_AppliTuto_ADMIN">                       
                   </menu-item>
	               <menu-item
                       id="menu.administration.secteurs.editionSecteur" 
                       visibleDansMenu="false" visibleDansPlan="false"
                       rolesAutorises="ROLE_AppliTuto_ADMIN">
                   </menu-item>
                </menu-item>  
	        </menu-item>
        </menu-item>
    </menu>
</pagelet>
